url: http://opensourpolitics.eu
baseurl:

# Site settings
title: Open Source Politics
email: virgile@opensourcepolitics.eu
description: "Solutions Civic Tech : nous mettons en place des outils open source et des méthodes efficaces pour faciliter vos prises de décisions collectives."

contact: static

collections:
  clients:
  refs:
    output: true
  jobs:
      output: true
  outils:
      output: true

# Team names, titles and social links
people:
- name: Alain Buchotte
  pic: 1
  position: Technique
  social:
    - title: github
      url: https://github.com/moustachu
    - title: linkedin
      url: #
    - title: envelope
      url: mailto:alain@opensourcepolitics.eu

- name: Virgile Deville
  pic: 2
  position: Projets
  social:
    - title: twitter
      url: https://twitter.com/virgiledeville
    - title: linkedin
      url: https://www.linkedin.com/in/virgiledeville
    - title: medium
      url: https://medium.com/@virgiledeville
    - title: envelope
      url: mailto:virgile@opensourcepolitics.eu

- name: Valentin Chaput
  pic: 3
  position: Conseil
  social:
    - title: twitter
      url: https://twitter.com/valentinchaput
    - title: linkedin
      url: https://www.linkedin.com/in/valentinchaput
    - title: medium
      url: https://medium.com/@ValentinChaput
    - title: envelope
      url: mailto:valentin@opensourcepolitics.eu


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/opensourcepol
  - title: facebook
    url: https://www.facebook.com/OpenSourcePolitics/
  - title: github
    url: https://github.com/OpenSourcePolitics
  - title: medium
    url: https://medium.com/open-source-politics
  - title: meetup
    url: https://meetup.com/fr-FR/Open-Source-Politics/


# Postal address (add as many lines as necessary)
address:
  - line: 32 rue des Cascades
  - line: 75020 Paris France

# Build settings
markdown: kramdown
permalink: pretty
