---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _refs-fr
  label: Refs-fr
  create: all
  match: "**/*"
- type: directory
  path: _refs-en
  label: Refs-en
  create: all
  match: "**/*"
- type: directory
  path: _jobs-en
  label: Jobs-en
  create: all
  match: "**/*"
- type: directory
  path: _jobs-fr
  label: Jobs-fr
  create: all
  match: "**/*"
- type: directory
  path: _outils
  label: Outils
  create: all
  match: "**/*"
- type: directory
  path: _offres-fr
  label: Offres-fr
  create: all
  match: "**/*"
- type: directory
  path: _offres-en
  label: Offres-en
  create: all
  match: "**/*"
- type: directory
  path: _post-fr
  label: Post-fr
  create: all
  match: "**/*"
- type: directory
  path: _post-en
  label: Post-en
  create: all
  match: "**/*"
- type: directory
  path: _blog-fr
  label: Blog-fr
  create: all
  match: "**/*"
- type: directory
  path: _blog-en
  label: Blog-en
  create: all
  match: "**/*"
- type: directory
  path: _clients
  label: Clients
  create: all
  match: "**/*"
- type: directory
  path: _members
  label: Members
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
